// قائمة الدول المنتقاة للعبة الجغرافيا — كل دولة: رمز ISO + اسم عربي + إحداثيات المركز (خط العرض/الطول)
// الإحداثيات تقريبية (مركز الدولة) وتكفي لحساب المسافة والاتجاه.
export const COUNTRIES = [
  // ——— العالم العربي والشرق الأوسط ———
  { iso: 'SA', ar: 'السعودية', lat: 23.9, lng: 45.1 },
  { iso: 'AE', ar: 'الإمارات', lat: 23.4, lng: 53.8 },
  { iso: 'QA', ar: 'قطر', lat: 25.3, lng: 51.2 },
  { iso: 'BH', ar: 'البحرين', lat: 26.0, lng: 50.5 },
  { iso: 'KW', ar: 'الكويت', lat: 29.3, lng: 47.5 },
  { iso: 'OM', ar: 'عُمان', lat: 21.5, lng: 55.9 },
  { iso: 'YE', ar: 'اليمن', lat: 15.5, lng: 48.0 },
  { iso: 'IQ', ar: 'العراق', lat: 33.2, lng: 43.7 },
  { iso: 'JO', ar: 'الأردن', lat: 31.3, lng: 36.2 },
  { iso: 'SY', ar: 'سوريا', lat: 34.8, lng: 38.9 },
  { iso: 'LB', ar: 'لبنان', lat: 33.9, lng: 35.9 },
  { iso: 'PS', ar: 'فلسطين', lat: 31.9, lng: 35.2 },
  { iso: 'EG', ar: 'مصر', lat: 26.8, lng: 30.8 },
  { iso: 'SD', ar: 'السودان', lat: 15.5, lng: 30.2 },
  { iso: 'LY', ar: 'ليبيا', lat: 26.3, lng: 17.2 },
  { iso: 'TN', ar: 'تونس', lat: 33.9, lng: 9.6 },
  { iso: 'DZ', ar: 'الجزائر', lat: 28.0, lng: 1.7 },
  { iso: 'MA', ar: 'المغرب', lat: 31.8, lng: -7.1 },
  { iso: 'MR', ar: 'موريتانيا', lat: 21.0, lng: -10.9 },
  { iso: 'SO', ar: 'الصومال', lat: 5.2, lng: 46.2 },
  { iso: 'DJ', ar: 'جيبوتي', lat: 11.8, lng: 42.6 },
  { iso: 'IR', ar: 'إيران', lat: 32.4, lng: 53.7 },
  { iso: 'TR', ar: 'تركيا', lat: 39.0, lng: 35.2 },

  // ——— آسيا ———
  { iso: 'CN', ar: 'الصين', lat: 35.9, lng: 104.2 },
  { iso: 'JP', ar: 'اليابان', lat: 36.2, lng: 138.3 },
  { iso: 'KR', ar: 'كوريا الجنوبية', lat: 36.5, lng: 127.9 },
  { iso: 'KP', ar: 'كوريا الشمالية', lat: 40.3, lng: 127.5 },
  { iso: 'IN', ar: 'الهند', lat: 22.0, lng: 79.0 },
  { iso: 'PK', ar: 'باكستان', lat: 30.4, lng: 69.3 },
  { iso: 'AF', ar: 'أفغانستان', lat: 33.9, lng: 67.7 },
  { iso: 'BD', ar: 'بنغلاديش', lat: 23.7, lng: 90.4 },
  { iso: 'TH', ar: 'تايلاند', lat: 15.9, lng: 100.9 },
  { iso: 'VN', ar: 'فيتنام', lat: 14.1, lng: 108.3 },
  { iso: 'PH', ar: 'الفلبين', lat: 12.9, lng: 121.8 },
  { iso: 'ID', ar: 'إندونيسيا', lat: -0.8, lng: 113.9 },
  { iso: 'MY', ar: 'ماليزيا', lat: 4.2, lng: 101.9 },
  { iso: 'SG', ar: 'سنغافورة', lat: 1.35, lng: 103.8 },
  { iso: 'KZ', ar: 'كازاخستان', lat: 48.0, lng: 66.9 },
  { iso: 'UZ', ar: 'أوزبكستان', lat: 41.4, lng: 63.6 },
  { iso: 'AZ', ar: 'أذربيجان', lat: 40.1, lng: 47.6 },
  { iso: 'GE', ar: 'جورجيا', lat: 42.3, lng: 43.4 },
  { iso: 'AM', ar: 'أرمينيا', lat: 40.1, lng: 45.0 },
  { iso: 'LK', ar: 'سريلانكا', lat: 7.9, lng: 80.8 },
  { iso: 'NP', ar: 'نيبال', lat: 28.4, lng: 84.1 },
  { iso: 'MM', ar: 'ميانمار', lat: 21.9, lng: 95.9 },
  { iso: 'MN', ar: 'منغوليا', lat: 46.9, lng: 103.8 },

  // ——— أوروبا ———
  { iso: 'GB', ar: 'بريطانيا', lat: 54.0, lng: -2.0 },
  { iso: 'FR', ar: 'فرنسا', lat: 46.6, lng: 2.5 },
  { iso: 'DE', ar: 'ألمانيا', lat: 51.2, lng: 10.4 },
  { iso: 'IT', ar: 'إيطاليا', lat: 42.8, lng: 12.8 },
  { iso: 'ES', ar: 'إسبانيا', lat: 40.2, lng: -3.7 },
  { iso: 'PT', ar: 'البرتغال', lat: 39.6, lng: -8.0 },
  { iso: 'NL', ar: 'هولندا', lat: 52.1, lng: 5.3 },
  { iso: 'BE', ar: 'بلجيكا', lat: 50.6, lng: 4.6 },
  { iso: 'CH', ar: 'سويسرا', lat: 46.8, lng: 8.2 },
  { iso: 'AT', ar: 'النمسا', lat: 47.6, lng: 14.1 },
  { iso: 'SE', ar: 'السويد', lat: 62.0, lng: 15.0 },
  { iso: 'NO', ar: 'النرويج', lat: 64.5, lng: 12.0 },
  { iso: 'FI', ar: 'فنلندا', lat: 64.0, lng: 26.0 },
  { iso: 'DK', ar: 'الدنمارك', lat: 56.0, lng: 9.5 },
  { iso: 'PL', ar: 'بولندا', lat: 52.1, lng: 19.4 },
  { iso: 'CZ', ar: 'التشيك', lat: 49.8, lng: 15.5 },
  { iso: 'GR', ar: 'اليونان', lat: 39.1, lng: 22.9 },
  { iso: 'RO', ar: 'رومانيا', lat: 45.9, lng: 24.9 },
  { iso: 'HU', ar: 'المجر', lat: 47.2, lng: 19.4 },
  { iso: 'UA', ar: 'أوكرانيا', lat: 48.4, lng: 31.2 },
  { iso: 'RU', ar: 'روسيا', lat: 61.5, lng: 100.0 },
  { iso: 'IE', ar: 'أيرلندا', lat: 53.2, lng: -8.1 },
  { iso: 'IS', ar: 'آيسلندا', lat: 64.9, lng: -19.0 },
  { iso: 'RS', ar: 'صربيا', lat: 44.0, lng: 21.0 },
  { iso: 'HR', ar: 'كرواتيا', lat: 45.1, lng: 15.2 },
  { iso: 'BG', ar: 'بلغاريا', lat: 42.7, lng: 25.5 },

  // ——— أفريقيا ———
  { iso: 'NG', ar: 'نيجيريا', lat: 9.1, lng: 8.7 },
  { iso: 'ET', ar: 'إثيوبيا', lat: 9.1, lng: 40.5 },
  { iso: 'KE', ar: 'كينيا', lat: 0.0, lng: 37.9 },
  { iso: 'TZ', ar: 'تنزانيا', lat: -6.4, lng: 34.9 },
  { iso: 'UG', ar: 'أوغندا', lat: 1.4, lng: 32.3 },
  { iso: 'GH', ar: 'غانا', lat: 7.9, lng: -1.0 },
  { iso: 'CI', ar: 'ساحل العاج', lat: 7.5, lng: -5.5 },
  { iso: 'SN', ar: 'السنغال', lat: 14.5, lng: -14.4 },
  { iso: 'ML', ar: 'مالي', lat: 17.6, lng: -4.0 },
  { iso: 'NE', ar: 'النيجر', lat: 17.6, lng: 8.1 },
  { iso: 'TD', ar: 'تشاد', lat: 15.4, lng: 18.7 },
  { iso: 'CM', ar: 'الكاميرون', lat: 5.7, lng: 12.7 },
  { iso: 'CD', ar: 'الكونغو الديمقراطية', lat: -2.9, lng: 23.6 },
  { iso: 'AO', ar: 'أنغولا', lat: -11.2, lng: 17.9 },
  { iso: 'ZM', ar: 'زامبيا', lat: -13.1, lng: 27.8 },
  { iso: 'ZW', ar: 'زيمبابوي', lat: -19.0, lng: 29.9 },
  { iso: 'MZ', ar: 'موزمبيق', lat: -18.7, lng: 35.5 },
  { iso: 'ZA', ar: 'جنوب أفريقيا', lat: -30.6, lng: 22.9 },
  { iso: 'NA', ar: 'ناميبيا', lat: -22.0, lng: 18.5 },
  { iso: 'BW', ar: 'بوتسوانا', lat: -22.3, lng: 24.7 },
  { iso: 'MG', ar: 'مدغشقر', lat: -18.8, lng: 46.9 },
  { iso: 'RW', ar: 'رواندا', lat: -1.9, lng: 29.9 },

  // ——— الأمريكتان ———
  { iso: 'US', ar: 'أمريكا', lat: 39.8, lng: -98.6 },
  { iso: 'CA', ar: 'كندا', lat: 56.1, lng: -106.3 },
  { iso: 'MX', ar: 'المكسيك', lat: 23.6, lng: -102.6 },
  { iso: 'BR', ar: 'البرازيل', lat: -14.2, lng: -51.9 },
  { iso: 'AR', ar: 'الأرجنتين', lat: -38.4, lng: -63.6 },
  { iso: 'CL', ar: 'تشيلي', lat: -35.7, lng: -71.5 },
  { iso: 'CO', ar: 'كولومبيا', lat: 4.6, lng: -74.3 },
  { iso: 'PE', ar: 'بيرو', lat: -9.2, lng: -75.0 },
  { iso: 'VE', ar: 'فنزويلا', lat: 6.4, lng: -66.6 },
  { iso: 'EC', ar: 'الإكوادور', lat: -1.8, lng: -78.2 },
  { iso: 'BO', ar: 'بوليفيا', lat: -16.3, lng: -63.6 },
  { iso: 'UY', ar: 'أوروغواي', lat: -32.5, lng: -55.8 },
  { iso: 'PY', ar: 'باراغواي', lat: -23.4, lng: -58.4 },
  { iso: 'CU', ar: 'كوبا', lat: 21.5, lng: -79.5 },
  { iso: 'GT', ar: 'غواتيمالا', lat: 15.8, lng: -90.2 },

  // ——— أوقيانوسيا ———
  { iso: 'AU', ar: 'أستراليا', lat: -25.3, lng: 133.8 },
  { iso: 'NZ', ar: 'نيوزيلندا', lat: -41.0, lng: 174.0 },
  { iso: 'PG', ar: 'بابوا غينيا الجديدة', lat: -6.3, lng: 143.9 },
  { iso: 'FJ', ar: 'فيجي', lat: -17.7, lng: 178.0 },
]

// بحث سريع بالرمز
export const BY_ISO = Object.fromEntries(COUNTRIES.map((c) => [c.iso, c]))

export function countryOf(iso) {
  return BY_ISO[iso] || null
}
